# Generated by Django 6.0.3 on 2026-03-30 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='descripteur',
            new_name='description',
        ),
    ]
