# Generated by Django 6.0.3 on 2026-04-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_remove_produit_date_ajout_remove_produit_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='quantite_vendue',
        ),
        migrations.AddField(
            model_name='vente',
            name='nom_client',
            field=models.CharField(default='Client Anonyme', max_length=100),
        ),
        migrations.AddField(
            model_name='vente',
            name='quantite',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
