# Generated by Django 6.0.2 on 2026-04-12 12:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['-date_modification'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AlterModelOptions(
            name='vente',
            options={'ordering': ['-date_vente'], 'verbose_name': 'Vente', 'verbose_name_plural': 'Ventes'},
        ),
        migrations.AddField(
            model_name='notification',
            name='lien',
            field=models.URLField(blank=True, help_text='Lien vers la page concernée'),
        ),
        migrations.AddField(
            model_name='notification',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produit',
            name='date_ajout',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='produit',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
        migrations.AddField(
            model_name='produit',
            name='seuil_alerte',
            field=models.IntegerField(default=5, help_text="Seuil d'alerte de stock bas"),
        ),
        migrations.AddField(
            model_name='vente',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='produit',
            name='quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.categorie'),
        ),
        migrations.CreateModel(
            name='HistoriqueStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('AJOUT', 'Ajout de produit'), ('MODIFICATION', 'Modification de stock'), ('VENTE', 'Vente'), ('ENTREE', 'Entrée de stock'), ('SORTIE', 'Sortie de stock'), ('SUPPRESSION', 'Suppression de produit'), ('AJUSTEMENT', 'Ajustement manuel')], max_length=20)),
                ('quantite_changee', models.IntegerField(default=0)),
                ('quantite_avant', models.IntegerField(blank=True, null=True)),
                ('quantite_apres', models.IntegerField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.produit')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de stock',
                'verbose_name_plural': 'Historiques de stock',
                'ordering': ['-date_action'],
            },
        ),
    ]
