# Generated by Django 6.0.3 on 2026-04-13 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_categorie_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historiquestock',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vente',
            options={'ordering': ['-date_vente']},
        ),
        migrations.RemoveField(
            model_name='historiquestock',
            name='details',
        ),
        migrations.RemoveField(
            model_name='historiquestock',
            name='quantite_apres',
        ),
        migrations.RemoveField(
            model_name='historiquestock',
            name='quantite_avant',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='lien',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='prix_total',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='quantite',
        ),
        migrations.AddField(
            model_name='vente',
            name='total_general',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historiquestock',
            name='type_action',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='seuil_alerte',
            field=models.IntegerField(default=5),
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.produit')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='gestion.vente')),
            ],
        ),
    ]
